spring:
  application:
    name: TripOps-Booking-Inventory-Management-Service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cache:
    type: redis
    redis:
      key-prefix: "travel::"
      use-key-prefix: true

server:
  port: ${SERVER_PORT:8080}

logging:
  pattern:
    level: "requestId=%X{requestId:-N/A} %5p"
