spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: ${DB_POOL_SIZE}
      minimum-idle: ${DB_MIN_IDLE}
      idle-timeout: ${DB_IDLE_TIMEOUT}
      max-lifetime: ${DB_MAX_LIFETIME}
      connection-timeout: ${DB_CONNECTION_TIMEOUT}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: ${REDIS_TIMEOUT}

server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}

razorpay:
  key: ${RAZORPAY_KEY}
  secret: ${RAZORPAY_SECRET}

bootstrap:
  admin:
    name: ${BOOTSTRAP_ADMIN_NAME}
    email: ${BOOTSTRAP_ADMIN_EMAIL}
    password: ${BOOTSTRAP_ADMIN_PASSWORD}

logging:
  level:
    root: INFO
    com.aj.travel: INFO
