CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE travel_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    location VARCHAR(255) NOT NULL,
    price NUMERIC(38, 2) NOT NULL,
    capacity INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_travel_packages_price_positive CHECK (price > 0),
    CONSTRAINT ck_travel_packages_capacity_positive CHECK (capacity > 0),
    CONSTRAINT ck_travel_packages_date_range CHECK (end_date >= start_date),
    CONSTRAINT ck_travel_packages_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    package_id BIGINT NOT NULL,
    guest_count INTEGER NOT NULL,
    total_price NUMERIC(38, 2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    booking_date TIMESTAMP NOT NULL,
    CONSTRAINT ck_bookings_guest_count_positive CHECK (guest_count > 0),
    CONSTRAINT ck_bookings_total_price_positive CHECK (total_price > 0),
    CONSTRAINT ck_bookings_status CHECK (status IN ('PENDING_PAYMENT', 'CONFIRMED', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    amount NUMERIC(38, 2) NOT NULL,
    payment_method VARCHAR(255) NOT NULL,
    razorpay_order_id VARCHAR(255),
    razorpay_payment_id VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    paid_at TIMESTAMP,
    CONSTRAINT uk_payments_booking_id UNIQUE (booking_id),
    CONSTRAINT uk_payments_razorpay_order_id UNIQUE (razorpay_order_id),
    CONSTRAINT uk_payments_razorpay_payment_id UNIQUE (razorpay_payment_id),
    CONSTRAINT ck_payments_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_payments_status CHECK (status IN ('CREATED', 'SUCCESS', 'FAILED', 'REFUNDED')),
    CONSTRAINT ck_payments_paid_at_status CHECK (
        (status = 'SUCCESS' AND paid_at IS NOT NULL)
        OR
        (status <> 'SUCCESS' AND paid_at IS NULL)
    )
);

CREATE INDEX idx_travel_packages_status ON travel_packages(status);
CREATE INDEX idx_bookings_user_id ON bookings(user_id);
CREATE INDEX idx_bookings_package_id ON bookings(package_id);
CREATE INDEX idx_bookings_status ON bookings(status);
CREATE INDEX idx_payments_booking_id ON payments(booking_id);
CREATE INDEX idx_payments_status ON payments(status);
